Vagrant.configure("2") do |config|

    config.vm.box = "bento/debian-11"
    config.vm.hostname = "Server"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "kferterb"
        vb.memory = 1024
    end
    config.vm.network "private_network", ip: "192.168.56.110"
    config.vm.provision "shell", privileged: false, path: "./scripts/setup.sh"
end