Vagrant.configure("2") do |config|
  config.vm.define "kferterb" do |kferterb|
    kferterb.vm.box = "generic/alpine317"
    kferterb.vm.network "private_network", ip: "192.168.56.110"
    kferterb.vm.synced_folder ".", "/sync"
    kferterb.vm.provision "Provisioning script", type: "shell", path: "./scripts/provision.sh"
    kferterb.vm.hostname = "kferterb"
    kferterb.vm.provider "virtualbox" do |vb|
      config.vm.network "forwarded_port", guest: 8080, host: 8080
      config.vm.network "forwarded_port", guest: 8888, host: 8888
      vb.name = "kferterb"
      vb.memory = 8192
      vb.cpus = 12
      end
  end
end
